//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageNumber.Presentation.ManageNumberService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ManageNumberService.IManageNumberService")]
    public interface IManageNumberService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageNumberService/Checkout", ReplyAction="http://tempuri.org/IManageNumberService/CheckoutResponse")]
        double Checkout(string number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageNumberService/Checkout", ReplyAction="http://tempuri.org/IManageNumberService/CheckoutResponse")]
        System.Threading.Tasks.Task<double> CheckoutAsync(string number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageNumberService/Checkin", ReplyAction="http://tempuri.org/IManageNumberService/CheckinResponse")]
        void Checkin(string number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageNumberService/Checkin", ReplyAction="http://tempuri.org/IManageNumberService/CheckinResponse")]
        System.Threading.Tasks.Task CheckinAsync(string number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageNumberService/VagasRestantes", ReplyAction="http://tempuri.org/IManageNumberService/VagasRestantesResponse")]
        int VagasRestantes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageNumberService/VagasRestantes", ReplyAction="http://tempuri.org/IManageNumberService/VagasRestantesResponse")]
        System.Threading.Tasks.Task<int> VagasRestantesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IManageNumberServiceChannel : ManageNumber.Presentation.ManageNumberService.IManageNumberService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ManageNumberServiceClient : System.ServiceModel.ClientBase<ManageNumber.Presentation.ManageNumberService.IManageNumberService>, ManageNumber.Presentation.ManageNumberService.IManageNumberService {
        
        public ManageNumberServiceClient() {
        }
        
        public ManageNumberServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ManageNumberServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManageNumberServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManageNumberServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double Checkout(string number) {
            return base.Channel.Checkout(number);
        }
        
        public System.Threading.Tasks.Task<double> CheckoutAsync(string number) {
            return base.Channel.CheckoutAsync(number);
        }
        
        public void Checkin(string number) {
            base.Channel.Checkin(number);
        }
        
        public System.Threading.Tasks.Task CheckinAsync(string number) {
            return base.Channel.CheckinAsync(number);
        }
        
        public int VagasRestantes() {
            return base.Channel.VagasRestantes();
        }
        
        public System.Threading.Tasks.Task<int> VagasRestantesAsync() {
            return base.Channel.VagasRestantesAsync();
        }
    }
}
